### ISSUE TITLE
Salvataggio misurazioni nel DB

### ISSUE THREAD

**Issue by marco-c** [kmos/centrocontrollo#11]
Al momento non le stiamo ancora salvando nel DB.

**Comment by kmos** [comment]
Volevo vedere un po' questa cosa, però non abbiamo defiinito come legare il dato "misurazione" con gli altri. O meglio, l'abbiamo fatto (mi pare volevi fare un array in nodo in stile document) ma nel progetto non è definito. Continuiamo in questa maniera?

**Comment by marco-c** [comment]
Questo l'ho assegnato a me, dato che ho fatto il resto della parte delle misurazioni.

**Comment by kmos** [comment]
Ah scusa, non l'avevo capito
Il 05/lug/2015 15:19, "Marco" notifications@github.com ha scritto:

**Comment by marco-c** [comment]
Non ti preoccupare ;)
