### ISSUE TITLE
Inviare la configurazione alla scheda nodo sensore

### ISSUE THREAD

**Issue by kmos** [kmos/centrocontrollo#13]
All'atto dell'inserimento di un nuovo nodo con tutto il suo set di sensori, si invia tramite la seriale la config al nodo sensore attaccato momentaneamente per la configurazione plug&play

**Comment by marco-c** [comment]
Potremmo anche fare che il nodo invia al centro di controllo la sua configurazione (così lasciamo al gruppo sicurezza l'onere di generare ID e chiave).

**Comment by kmos** [comment]
vediamo come si evolvono le cose.

**Comment by kmos** [comment]
fixed with commit cc48cc8d5e3a6d1959a3479f2cddbb8ebd6f9797

**Comment by marco-c** [comment]
Quel commit non risolve questa issue.

**Comment by kmos** [comment]
scusa hai ragione, stavo sballato
