### ISSUE TITLE
gestire gli allarmi tramite finestre popup

### ISSUE THREAD

**Issue by kmos** [kmos/centrocontrollo#14]

**Comment by marco-c** [comment]
http://getbootstrap.com/components/#alerts

**Comment by kmos** [comment]
for space monkeys http://nakupanda.github.io/bootstrap3-dialog/

**Comment by marco-c** [comment]
Queste però sono dialog modali, con cui devi per forza interagire (anche per chiuderle). Gli alert invece possiamo farli comparire in basso e l'utente può ignorarli se vuole.

**Comment by kmos** [comment]
ottimo (y)
