### ISSUE TITLE
Visualizzare la topologia della rete

### ISSUE THREAD

**Issue by kmos** [kmos/centrocontrollo#15]
Graficare la topologia della rete.

Librerie utili:
http://sigmajs.org/

**Comment by kmos** [comment]
Ho pensato un po' a come si potrebbe creare il json adatto ad essere graficato con le librerie sigmajs. Basandomi su questo esempio:

``` json
{
  "nodes": [
    {
      "id": "n0",
      "label": "A node",
      "x": 0,
      "y": 0,
      "size": 3
    },
    {
      "id": "n1",
      "label": "Another node",
      "x": 3,
      "y": 1,
      "size": 2
    },
    {
      "id": "n2",
      "label": "And a last one",
      "x": 1,
      "y": 3,
      "size": 1
    }
  ],
  "edges": [
    {
      "id": "e0",
      "source": "n0",
      "target": "n1"
    },
    {
      "id": "e1",
      "source": "n1",
      "target": "n2"
    },
    {
      "id": "e2",
      "source": "n2",
      "target": "n0"
    }
  ]
}
```

dobbiamo creare due array: Nodes e edge. Nodes corrisponde al nodo e al suo posizionamento, edge l'interconnessione tra nodi. Per quanto riguarda il primo array, ho pensato che 

``` json
  "nodes":
    {
      "id": "n0",
      "label": "A node",
      "x": 0,
      "y": 0,
      "size": 3
    }
```

Id e label, si ottengono facilmente (id noto, tipologia di nodo), per il size potremmo anche mettere tutti uguali o solo 3 differenti taglie (nodo centrale, router, nodo). Per la posizione X,Y, dato il percorso, X può essere popolato attraverso il ramo di appartenenza e Y con la sua lontananza dal nodo centrale.
Per quanto riguarda edge

``` json
  "edges":
    {
      "id": "e0",
      "source": "n0",
      "target": "n1"
    }
```

id può essere semplicemente un valore incrementale, "source" il nodo del quale viene definito il percorso, e "target" il suo next hop. 

In questo modo, l'unione di tutti i percorsi, dovrebbe creare una mappa temporanea dei link.

**Comment by marco-c** [comment]
Mi sembra che x e y non siano obbligatorie, ti posiziona i nodi automaticamente se le ometti.

**Comment by marco-c** [comment]
P.S.: non c'è bisogno di codificare il grafo in JSON, si può semplicemente utilizzare quest'API: https://github.com/jacomyal/sigma.js/wiki/Graph-API

**Comment by kmos** [comment]
Mi son perso un po' di cose XD. Comunque attraverso le API che hai linkato, possiamo creare la mappa di volta in volta. L'unica cosa, credo siano necessari X, Y altrimenti piazzi il nodo ovunque senza dare l'idea della distanza dal nodo centrale

**Comment by marco-c** [comment]
Possiamo iniziare con la visualizzazione di base e poi aggiungere il posizionamento in seguito.
Probabilmente non possiamo avere un'idea di come sono posizionati i nodi fisicamente, quindi potremmo semplicemente mettere il nodo centrale sopra a tutto e far posizionare alla libreria il resto dei nodi (se è possibile farlo).

**Comment by kmos** [comment]
ottimo, allora.

**Comment by kmos** [comment]
Io direi di spostare il grafico in un altra pagina, poiché all'aumentare dei nodi occupa tutta la pagina e non si vede il resto
