### ISSUE TITLE
Modificare il monitor in modo da aggiornare i valori

### ISSUE THREAD

**Issue by kmos** [kmos/centrocontrollo#20]
All'arrivo di una rilevazione per lo stesso sensore, il vecchio valore dovrebbe cambiare con quello nuovo e non accodarsi.

**Comment by marco-c** [comment]
L'ho fatto così perché potrebbe interessare vedere i vari valori (ad esempio se uno ha impostato un periodo al sensore, probabilmente vuole vedere cosa sta misurando e come evolvono le misurazioni)

**Comment by kmos** [comment]
Dici? Ok
Il 05/lug/2015 12:16, "Marco" notifications@github.com ha scritto:

**Comment by kmos** [comment]
funzionalità in linea con le specifiche:

**Comment by kmos** [comment]
Funzionalità in linea con le specifiche:
- dare la possibilità di vedere le misurazioni in live e allo stesso tempo lo storico delle misurazioni passate senza aggiornarle quindi al nuovo valore.
