### ISSUE TITLE
Collegare la pagina dei nodi con il back-end

### ISSUE THREAD

**Issue by marco-c** [kmos/centrocontrollo#4]
Al momento la tabella è statica e il form di aggiunta nodo non è collegato con il server.

**Comment by kmos** [comment]
ok, incomincio con questo...

**Comment by marco-c** [comment]
Magari mettici dei dati statici di prova per iniziare (che poi sarà effettivamente quello che faremo quando avremo i dati delle schede di tutti).

**Comment by kmos** [comment]
eh si

**Comment by marco-c** [comment]
Questo è completo ora?

**Comment by kmos** [comment]
In teoria si, quando si inserisce un nodo vorrei mettere anche la parte di
inserimento sensore, ma senza la sicurezza sui dati mi sono fermato...
Il 05/lug/2015 15:19, "Marco" notifications@github.com ha scritto:

**Comment by marco-c** [comment]
La parte di inserimento nodo non è strettamente necessaria per il 14.

**Comment by kmos** [comment]
fixed
