### ISSUE TITLE
Aggiungere parte di configurazione sensore alla pagina dei sensori

### ISSUE THREAD

**Issue by marco-c** [kmos/centrocontrollo#7]

**Comment by kmos** [comment]
in linea teorica, se è statica, non dovremmo poter modificare la configurazione di un sensore. Al massimo possiamo inibire l'ascolto...

**Comment by marco-c** [comment]
Non avevamo deciso che era possibile cambiare la configurazione di un sensore? Tipo threshold, periodo, etc.
La configurazione di un nodo statica (cioè ci sono sempre gli stessi sensori), ma la configurazione di un sensore dinamica.

Se ricordo male, chiudi l'issue.

**Comment by kmos** [comment]
Hai ragione. Sono io che mi ricordo male. Bene scriverlo.

Il 05/lug/2015 12:14, "Marco" notifications@github.com ha scritto:

**Comment by marco-c** [comment]
Quindi, in generale dobbiamo: salvare la configurazione nel DB e inviarla alla scheda (aspettandoci un ACK?).

**Comment by kmos** [comment]
Si, (per l ack non saprei)
Il 05/lug/2015 15:21, "Marco" notifications@github.com ha scritto:

**Comment by ing-raf** [comment]
Si assume che:
- la configurazione dei Nodi Sensore è **STATICA**, ossia sono determinati e noti a tempo di compilazione:
  - il numero di sensori connessi a ciascun Nodo Sensore;
  - le caratteristiche fisiche di ciascun sensore, ovvero classe, collegamento, eventualmente indirizzo, e in particolare **periodo di lettura fisico**, ossia in terminologia tecnica "_ogni quanto tempo il sensore rompe il cazzo_";
- il Centro di Controllo conosce questa configurazione, e non ci sono discrepanze fra quanto noto al Centro di Controllo - e quindi contenuto nel DB - e quanto noto al Nodo Sensore - e quindi contenuto nel suo file di configurazione -

Viceversa (ma questo solo nella versione _Edition_ del Nodo Sensore, che deve essere ancora sviluppata) la configurazione a livello applicativo è **DINAMICA**, ossia il Centro di Controllo specifica, _per ciascun sensore connesso al Nodo Sensore_ (che conosce tutti per le assunzioni di cui sopra):
- il **periodo di lettura logico**, cioè il periodo con il quale il dato fornito dal sensore deve essere campionato e inviato al centro di controllo;
- la priorità del sensore;
- se il sensore è configurato per generare un allarme nel caso in cui un valore letto sia esterno a una prefissata soglia;
- i limiti inferiore e superiore oltre i quali inviare la segnalazione di allarme;
- se i dati del sensore sono confidenziali, cioè devono essere cifrati prima dell'invio al Centro di Controllo.

Un sensore si comporta da sensore **ASINCRONO**, ossia non invia alcun dato a meno che non viene esplicitamente interrogato dal Centro di Controllo, se il suo **periodo di lettura logico** viene impostato pari a 0.

Nella versione attuale del codice del Nodo Sensore (v.0.2):
- È possibile specificare le soglie anche se il sensore non è configurato per lanciare un allarme; in questo caso le soglie non hanno alcun effetto.
- Viceversa la funzione `setReadPeriod()` controlla che il periodo di lettura logico sia non superiore del periodo di lettura fisico, se quest'ultimo è non nullo; in tal caso il periodo di lettura logico viene impostato pari al periodo di lettura fisico.

**Comment by kmos** [comment]
Fixed cc48cc8d5e3a6d1959a3479f2cddbb8ebd6f9797

**Comment by marco-c** [comment]
Manca la parte di invio del messaggio al nodo centrale, puoi aprire una nuova issue per quello o riaprire questa?

**Comment by marco-c** [comment]
Fatto in 387cdbb9ac04ad723974fe1dffe908e951236952.
